### ISSUE TITLE
Please Enhance the Scalability to Apply Also to RichText

### ISSUE THREAD

**Issue by hajiung25** [TykanN/xtyle#1]
Hello, I am currently making good use of the package you've provided. However, when specifying styles for each character using RichText and TextSpan, I cannot use XtyleText, and it is inconvenient to have to insert the font family manually for each one. Is there a solution for this case, or do you have any plans to upgrade the package in the future?

**Comment by TykanN** [comment]
You can use `XtyleText.rich` constructor.
However, I have confirmed that the 0.1.3 version of the `Xtyle.rich` widget is not working as intended.
from version 0.2.0, You can use it  the same way as Text.rich.

```dart
XtyleText.rich(
                TextSpan(
                  text: 'Hello',
                  children: [
                    TextSpan(text: ' 안녕', style: TextStyle(color: Colors.red)),
                    TextSpan(text: ' World', style: TextStyle(color: Colors.blue)),
                  ],
                  style: TextStyle(fontWeight: FontWeight.bold),
                ),
                style: TextStyle(fontSize: 24), // default text style
              )

```

**Comment by TykanN** [comment]
위 방식에 문제가 있거나 해결되지 않는 케이스가 있다면 언제든지 이슈 다시 열어주세요 👍
